### ISSUE TITLE
ethers.framework is missing and how to compile?

### ISSUE THREAD

**Issue by xuncai** [ethers-io/ethers.objc#11]
Hi guys, 
I am pretty new to ETH IOS.
I am wondering how to compile this project and run it at least?

I am having problem like 
#import <ethers/Address.h>  not found.
And the ethers.framework is missing.

Thanks for the help
Xun

**Comment by ricmoo** [comment]
Heya!

Yes, I need to add build directions to the README.

You need to clone both repositories from our GitHub Page:
- [ethers.objc library](https://github.com/ethers-io/ethers.objc)
- [Ethers Wallet Application](https://github.com/ethers-io/EthersWallet-ios)

Place both those in the same directory, and open the Xcode project in the **EthersWallet-ios** and you should be off to the races. The Application references the library using ../ethers.objc, so if you use the ZIP file instead of `git clone`, you may have to drop the `-master` the ZIP file adds.

Let me know if you have any more issues. I'll leave this issue open for a couple days unless you close it. :)

**Comment by xuncai** [comment]
Hey Ricmoo, really thx for your quick response. Trying it now will let you know. Once it work I can do some screenshot and tutorial to other dev! Good work
